### ISSUE TITLE
[bug] 导航栏背景显示错误

### ISSUE THREAD

**Issue by WHYBBE** [Direct5dom/WSAFileLink#1]
问题：

![image](https://github.com/Direct5dom/WSAFileLink/assets/40510346/082fc962-4636-4961-8606-56d9b3885d7c)

如何复现：

点击导航栏的“汉堡”图标即可触发

如何解决：

修改App.xaml中资源的拼写错误

预期行为：

![image](https://github.com/Direct5dom/WSAFileLink/assets/40510346/f9ba9ee5-32c2-4d02-8c26-5fd401f8731d)

**Comment by sixiaolong1117** [comment]
感谢您的反馈，#2 已合并。

**Comment by sixiaolong1117** [comment]
突然发现这其实并不是拼写错误，而是官方在这里的写法就是`Pane`，修改成`Panel`其实是让这几行代码无效化了。
会出现你报告的问题其实是因为我没有在浅色模式下做足够多的测试，那个半透明效果其实是我当初有意做的，但是在浅色背景下呈现的效果不是很如意，去掉透明效果后反而更好看了。（这是我的问题，在之后的开发中我会注意）
另外微软官方其实在新版的WSA中直接提供了文件夹映射的功能，这个基于ADB的程序意义已经不大了。
不过还是要谢谢你提交PR :)

**Comment by WHYBBE** [comment]
> 突然发现这其实并不是拼写错误，而是官方在这里的写法就是`Pane`，修改成`Panel`其实是让这几行代码无效化了。
> 会出现你报告的问题其实是因为我没有在浅色模式下做足够多的测试，那个半透明效果其实是我当初有意做的，但是在浅色背景下呈现的效果不是很如意，去掉透明效果后反而更好看了。（这是我的问题，在之后的开发中我会注意）
> 另外微软官方其实在新版的WSA中直接提供了文件夹映射的功能，这个基于ADB的程序意义已经不大了。
> 不过还是要谢谢你提交PR :)

哈哈，尴尬了，winui3没那么熟，只是我觉得那个效果特别奇怪，一无效化反而好看了（当然我也不知道那个是无效化）

你这个也解决了我的困惑，我当时就发现直接改那个颜色是有效果的，但怎么改都不好看，还以为是单词拼错了，但这里就矛盾了拼错了改颜色怎么会有效果呢（其实是效果没那么好看）

有时候不想直接映射也不想手打命令你这个还是有用的😁
